version: '2'
services:
    sir_tp6-mysql:
        container_name: sir_tp6-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/sir_tp6/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sir_tp6
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1
